# Site settings
title: Yo! This is Narella'blog
email: zhangnanmei@126.com
description: > #personal blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://narellazhang.github.io" # the base hostname & protocol for your site

github_username:  narellazhang

# Build settings
markdown: kramdown
